"""Deterministic mock LLM provider.

Used exclusively by automated tests (see `app.core.config.LLMProviderKind.MOCK`)
so the full LangGraph workflow can be exercised end-to-end without a live
Ollama server. Each agent embeds an `[AGENT:<ROLE>]` marker in its system
prompt; this provider matches on that marker to return a realistic,
schema-correct canned JSON response for that specific agent step.

Production code must never depend on this class -- it exists purely to
make `OllamaProvider` swappable and the workflow testable in isolation.
"""

from __future__ import annotations

import re
from collections.abc import AsyncIterator

from app.llm.base import LLMMessage, LLMProvider, LLMResponse

_MARKER_RE = re.compile(r"\[AGENT:(\w+)\]")

_CANNED_RESPONSES: dict[str, str] = {
    "PLANNER": """
{
  "items": [
    {"title": "Set up project structure", "description": "Create package layout, entry point, and configuration files.", "order": 0, "depends_on": []},
    {"title": "Implement core logic", "description": "Implement the primary feature requested by the user.", "order": 1, "depends_on": []},
    {"title": "Add tests", "description": "Add unit tests covering the core logic.", "order": 2, "depends_on": []}
  ]
}
""",
    "ARCHITECT": """
{
  "summary": "A small single-module application with a clear separation between core logic and the entry point.",
  "components": [
    {"name": "core", "responsibility": "Implements the primary business logic.", "interfaces": ["run(input) -> output"], "dependencies": []},
    {"name": "cli", "responsibility": "Provides a command-line entry point.", "interfaces": ["main()"], "dependencies": ["core"]}
  ],
  "tech_choices": {"language": "python", "test_framework": "pytest"},
  "file_layout": ["app/core.py", "app/cli.py", "tests/test_core.py", "README.md"]
}
""",
    "CODER": """
{
  "files": [
    {
      "path": "app/core.py",
      "change_type": "create",
      "language": "python",
      "content": "\\"\\"\\"Core application logic.\\"\\"\\"\\n\\n\\ndef run(value: int) -> int:\\n    \\"\\"\\"Double the given value.\\"\\"\\"\\n    return value * 2\\n"
    },
    {
      "path": "tests/test_core.py",
      "change_type": "create",
      "language": "python",
      "content": "from app.core import run\\n\\n\\ndef test_run_doubles_value():\\n    assert run(3) == 6\\n"
    }
  ]
}
""",
    "REVIEWER": """
{
  "verdict": "approved",
  "findings": [],
  "summary": "Code is clean, well-typed, and matches the architecture plan. No blocking issues found."
}
""",
    "TESTER": """
{
  "verdict": "passed",
  "cases": [
    {"name": "tests/test_core.py::test_run_doubles_value", "passed": true, "output": "1 passed in 0.01s"}
  ],
  "summary": "All tests passed."
}
""",
    "DOCUMENTATION": """
{
  "readme": "# Generated Project\\n\\nThis project was generated by the Multi-Agent Coding Assistant.\\n\\n## Usage\\n\\n```bash\\npython -m app.cli\\n```\\n"
}
""",
}


class MockProvider(LLMProvider):
    """Returns deterministic, schema-valid JSON keyed off the agent marker."""

    def __init__(self, canned_overrides: dict[str, str] | None = None) -> None:
        self._responses = {**_CANNED_RESPONSES, **(canned_overrides or {})}

    def _resolve(self, messages: list[LLMMessage]) -> str:
        for message in messages:
            if message.role != "system":
                continue
            match = _MARKER_RE.search(message.content)
            if match and match.group(1) in self._responses:
                return self._responses[match.group(1)]
        return '{"result": "ok"}'

    async def generate(
        self,
        messages: list[LLMMessage],
        *,
        temperature: float | None = None,
    ) -> LLMResponse:
        content = self._resolve(messages)
        return LLMResponse(content=content, model="mock-model", raw={"mock": True})

    async def stream(
        self,
        messages: list[LLMMessage],
        *,
        temperature: float | None = None,
    ) -> AsyncIterator[str]:
        content = self._resolve(messages)
        for chunk in content.split():
            yield chunk + " "

    async def health_check(self) -> bool:
        return True
